### ISSUE TITLE
Feature: Docker build system

### ISSUE THREAD

**Issue by robhaswell** [madcowfred/evething#70] opened 2014-07-03 15:28 UTC
EVEthing is somewhat difficult to deploy. Modern containerisation can streamline this process by exposing a single container with a complete EVEthing instance inside it.

This container can expose a single web service while containing all the dependencies.

Whenever EVEthing is updated the container can be recreated and re-deployed.

**Comment by Gillingham** [comment] 2014-07-03 17:42
Duplicate of pull request #71

**Closed as completed by Gillingham** 2014-07-03 17:42 UTC
Labels: Feature
