### ISSUE TITLE
wsgi.py path

### ISSUE THREAD

**Issue by AMoo** [madcowfred/evething#6] opened 2012-09-12 17:54 UTC
I had to edit wsgi.py so that :

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(**file**), '..')))

now reads

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(**file**))))

or I get an error 

ImportError: Could not import settings 'evething.settings' (Is it on sys.path?): No module named settings

**Comment by madcowfred** [comment] 2012-09-15 10:33
Modified the wsgi.py to actually match what is suggested for Django 1.4 with e28122ae30f3c92c4391c5242eb25ad329aab74c, could you test? Works with uWSGI, don't have a Apache+mod_wsgi setup handy.

**Comment by AMoo** [comment] 2012-09-30 19:28
No, same error.  200 when trying to load page and the following in error log

ImportError: Could not import settings 'evething.settings' (Is it on sys.path?): No module named evething.settings

**Comment by madcowfred** [comment] 2013-02-28 05:06
I can't reproduce this using Python 2.6 and Django 1.4, the current wsgi.py file works fine for me. Closing ticket.

**Comment by Tupsi** [comment] 2013-03-07 12:08
I also had to modify my wsgi.py in order to get this running. Actually had two issues, one with the path like the OP, the 2nd problem you only get when following your installation guide and install into a virtualenv; that way you get a lot of complaints when starting about missing packages (everything not installed outside the virtualenv).

I had to add the following to wsgi.py

import site
site.addsitedir('/[PATH to my virtualenv]/lib/python2.7/site-packages')

**Comment by madcowfred** [comment] 2013-03-10 14:33
I've just moved wsgi.py to the correct path of /evething/wsgi.py, can you try bbd5145 with the following change to WSGIDaemonProcess?

WSGIDaemonProcess evething threads=2 user=nobody python-path=/path/to/env/lib/python2.7/site-packages

**Comment by Tupsi** [comment] 2013-03-10 17:56
This change left my apache total broke giving me a 
"
Page unavailable

Sorry, but the requested page is unavailable due to a server hiccup.

Our engineers have been notified, check back later.
"
which I have never seen before in that way. It seems that it doesnt like the python-path in the site config at all. Although I was not sure if you moved it ot evething/evething/wsgi.py or evething/wsgi.py. In both cases the error log complained about 

ImportError: Could not import settings 'evething.settings' (Is it on sys.path?): No module named evething.settings

until I added my changes back in to add the path, but then got your strange Apache error until I removed the python-path again out of the apache config file

**Comment by Tupsi** [comment] 2013-03-10 17:58
and to clarfiy, this is how my current working wsgi.py ( sitting in evething/evething/) looks like:

import os
import sys
import site
site.addsitedir('/opt/thingenv/lib/python2.7/site-packages')

# try using cdecimal for faster Decimal type

try:
    import cdecimal
except ImportError:
    pass
else:
    sys.modules["decimal"] = cdecimal

#sys.path.append(os.path.abspath(os.path.join(os.path.dirname(**file**), '..')))
#os.environ['DJANGO_SETTINGS_MODULE'] = 'evething.settings'
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'evething.settings')

import djcelery
djcelery.setup_loader()

#import django.core.handlers.wsgi
#application = django.core.handlers.wsgi.WSGIHandler()

# This application object is used by the development server

# as well as any WSGI server configured to use this file.

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()

# Needed for Apache to find the settings file

base = os.path.dirname(os.path.dirname(**file**))
base_parent = os.path.dirname(base)
sys.path.append(base)

**Comment by madcowfred** [comment] 2013-03-10 23:24
How annoying, I'll install Apache+mod_wsgi and try to work out what the issue is today. I haven't used it since I switched to using virtualenv and nginx+uwsgi seems to just work without any major dramas :(

**Comment by madcowfred** [comment] 2013-03-11 03:38
Right, the following line in my Apache vhost config seemed to make things work:

WSGIDaemonProcess evething threads=1 user=freddie python-path=/home/freddie/env26/lib/python2.6/site-packages:/home/freddie/git/evething

mod_wsgi is kinda weird. I'll update the terrible README shortly.

**Closed as completed** 2013-05-09 00:16 UTC
